spring:
  datasource:
    url: jdbc:postgresql://promotion-database-1.c3hjrogbshlp.us-east-2.rds.amazonaws.com/postgres
    username: postgres_admin
    password: vbrtwe53
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db.migration
  jpa:
    show-sql: true
    open-in-view: false

server:
  servlet:
    context-path: /api

logging.level:
  org.flyway: info
  org.hibernate.SQL: debug
  org.hibernate.type.descriptor.sql: trace

aws:
  access-key: AKIAVEA3ZIKRJWT6DZMC
  secret: 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
  homeworks-path: promotion-project/homeworks

jwt:
  key: promotionProjectKeypromotionProjectKeypromotionProjectKeypromotionProjectKeypromotionProjectKey
  issuer: promotionProject
