spring:
  datasource:
    url: jdbc:postgresql://promotion-database-1.c3hjrogbshlp.us-east-2.rds.amazonaws.com:5432/postgres
    username: shmigel
    password: vbrtwe53
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db.migration


logging:
  level:
    org.flyway: info